a = input('digite algo: ')
print('O tipo primitivo desse valor é {}'.format(type(a)))
print('Só tem espacos: {} '.format(a.isspace()))
print('é um número: {}'.format(a.isnumeric()))
print('é alfabético: {} '.format(a.isalpha()))
print('é alfanúmerico: {} '.format(a.isalnum()))
print('está em maiúsculas: {} '.format(a.isupper()))
print('está em minúsculas: {} '.format(a.islower()))
print('está capitalizada: {}'.format(a.istitle()))